[package]
name = "HelloRustWorld"
version = "0.1.0"
authors = ["louvre2489 <louvre2489@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.36"
clap = "=3.0.0-beta.2"
